title: InScight
description: "InScight is a student-run online magazine hosted by IISER Kolkata, dedicated to making science accessible and engaging for a general audience." # Primarily for SEO.
url: "https://scicomm.iiserkol.ac.in" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ''
destination: ./docs
logo: "/assets/global/darkBanner.png"
digest-excerpt: "In Insight Digest, we showcase the latest happenings in science research."
digest-truncate-length: 330
archives: # key-value pairs that list the categories of posts that need to be listed in the archives page
  article: "Articles"
  interview: "Interviews"
  digest: "Insight Digest"
archive-year: # range of years to archive
  start: 2024
  end: 2025
color-emoji:
  article: "🧬"
  interview: "🎙️"
  crossword: "🎳"
  comic: "🖍️"
  author: "🧑‍🔬"
  browse: "🥽"
  download: "⤵️"
  old: "🗓️"
  alert: "🧩"
  cloud: "☁️"
  desktop: "🖥️"
  copyright: "©️"
  speaker: "📢"
  newspaper: "🗞️"
  fire: "🔥"
  star: "🌠"
  flask: "⚗️"
  scientist: "🧑‍🔬"
  clip: "📎"
  hourglass: "⏳"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: posts
      excerpt: ""
      author-image: false
  - scope:
      path: "_posts/*/*-digest.md"
      type: posts
    values:
      layout: digest
      author-image: false
      excerpt: ""
  - scope:
      path: "_posts/*/*-quiz.md"
      type: posts
    values:
      layout: quiz
      category: quiz
      author-image: false
      authors: ['Alekhya Kundu']
      excerpt: ""
  - scope:
      path: "_posts/*/*-whoami.md"
      type: posts
    values:
      layout: whoami
      category: whoami
      author-image: false
      excerpt: ""
  - scope:
      path: "_posts/*/*-linkedlist.md"
      type: posts
    values:
      layout: linkedlist
      category: linkedlist
      author-image: false
      authors: ['Alekhya Kundu']
      excerpt: ""
  - scope:
      path: "_posts/*/*-crossword.md"
      type: posts
    values:
      layout: crossword
      category: crossword
      author-image: false
      excerpt: ""
      authors: ['Alekhya Kundu']
  - scope:
      path: "pages/*"
    values:
      layout: pages
      excerpt: ""
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  toc_levels: 1..2
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  math_engine: katex
  parse_block_html: false
  highlighter: rouge
plugins:
  - jekyll-sitemap
socials:
  - facebook: https://www.facebook.com/inscightmagazine
  - instagram: https://www.instagram.com/inscight_iiserkolkata/
  - twitter: https://x.com/InScightIISERK
navbar:
  Magazine: "/magazine/"
  Games: "/games/"
  Submit: "/submit/"
  About: "/about/"
navbarLong:
  Magazine: "/magazine/"
  Archives: "/archives/"
  Games: "/games/"
  Opportunities: "/opportunities/"
  Comics: "/comics/"
  Submit: "/submit/"
  About: "/about/"
openings-sheet: "https://docs.google.com/spreadsheets/d/e/2PACX-1vS8Ae9TtmUWrWC3yx0dg_B7uhFcEX2MvahcpjWUGxh6092I3ZgnK92WYiqbGTN-Q7kVrIQzy1DS3HBh/pub?output=tsv"
